#!/usr/bin/env bash
## makefile:fmt This script is used to run the tests

PROJECT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && cd .. && pwd )
export PYTHONPATH=$PROJECT_DIR/src:$PYTHONPATH

if ! command -v pytest &> /dev/null; then
    echo "pytest is not installed. Installing..."
    pip install pytest
fi

echo "Running tests..."

pytest --rootdir=$PROJECT_DIR src/tests -vvv

echo "Tests completed."